name: Changelog Enforcer

on:
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  changelog-enforcer:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: dangoslen/changelog-enforcer@v3
