name: Changelog Enforcer

on:
  pull_request_target:
    branches:
      - main
      - release-v*

jobs:
  changelog-enforcer:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@v3
