name: Dependency Review

on:
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v2
