name: Dependency Review

on:
  pull_request_target:
    branches:
      - main
      - release-v*

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v2
